#!/bin/sh
#
echo "********************************************************"
echo "*                                                      *"
echo "* Welcome to Slyk Onyx by KiddaC                       *"
echo "*                                                      *"
echo "* Other Skins Available                                *"
echo "*                                                      *"
echo "* Slyk 1 HD - Sky Skin                                 *"
echo "* Slyk Q - Sky Q Skin                                  *"
echo "* VSkin HD - Plum Virgin Skin                          *"
echo "* VSkin Bolt - Blue Virgin Skin                        *"
echo "*                                                      *"
echo "* Latest versions and support for these skins is       *"
echo "* available via linuxsat-support.com                   *"
echo "*                                                      *"
echo "* If you would like to treat me to a beer for all my   *"
echo "* time and effort visit https://slyk1hd.yolasite.com   *"
echo "* or google slyk kiddac                                *"
echo "*                                                      *"
echo "* Thank you and Enjoy. KiddaC                          *"
echo "*                                                      *"
echo "********************************************************"
echo " "

echo "Installing..."
sleep 15s # Waits 15 seconds.

rm -f "/usr/lib/enigma2/python/Components/Converter"/*.py
rm -f "/usr/lib/enigma2/python/Components/Renderer"/*.py
rm -f "/usr/lib/enigma2/python/Components/Screens"/*.py

exit 0

